/**
 * All user-facing copy lives here, in German (Sie-Form).
 * One place to edit when wording needs to change.
 */
export const strings = {
  common: {
    loading: 'Wird geladen…',
    retry: 'Erneut versuchen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    confirm: 'Bestätigen',
    noResults: 'Keine Treffer',
  },
  brandPicker: {
    title: 'Willkommen',
    subtitle: 'Wählen Sie Ihre Marke aus',
    continue: 'Weiter',
  },
  login: {
    title: 'Anmelden',
    subtitle: 'Melden Sie sich mit Ihren Zugangsdaten an',
    username: 'Benutzername',
    password: 'Passwort',
    stayLoggedIn: 'Angemeldet bleiben',
    submit: 'Anmelden',
    demoHint: 'Demo: Beliebige Eingaben funktionieren',
  },
  tabs: {
    start: 'Start',
    karte: 'Karte',
    scanner: 'Scanner',
    maerkte: 'Märkte',
    produkte: 'Produkte',
    liste: 'Liste',
    kasse: 'Kasse',
    inventar: 'Inventar',
  },
  start: {
    greeting: (userName: string) => `Willkommen, ${userName}`,
    quickAccess: 'Schnellzugriff',
    offersTeaserGeneral: 'Allgemeine Angebote',
    tileKarte: 'Kundenkarte',
    tileRechnungen: 'Rechnungen',
    tileScannerAway: 'Scan/Verfügb.',
    tileScannerInStore: 'Scan & Go',
    tileRueckverguetung: 'Rückvergütung',
    inventoryAlertTitle: (count: number) => `${count} ${count === 1 ? 'Artikel' : 'Artikel'} kritisch nachzubestellen`,
    inventoryAlertHint: 'Bestand reicht nicht bis morgen.',
    inventoryAlertAction: 'Inventar prüfen',
  },
  karte: {
    title: 'Digitale Kundenkarte',
    customerNumber: 'Kunden-Nr.',
    flipHint: 'Tippen für Details',
    backTitle: 'Kartendetails',
    validUntil: 'Gültig bis',
    business: 'Betrieb',
    backNote: 'Diese Karte ist nur in Verbindung mit einem gültigen Lichtbildausweis gültig.',
    zoom: 'Barcode vergrößern',
    zoomHint: 'Zum Scannen an der Kasse vorzeigen',
    close: 'Schließen',
    edeka: {
      tagline: 'Qualität. Die ankommt.',
      cardLabel: 'KUNDENKARTE',
      role: 'Handelshof-Mitarbeiter',
    },
    handelshof: {
      cardLabel: 'Kundenausweis',
      role: 'PERSONAL',
      address: 'Handelshof Rheinbach GmbH & Co. KG · Kleinaltendorfer Weg 2 · 53359 Rheinbach',
    },
  },
  maerkte: {
    title: 'Märkte',
    nearestBranch: 'Nächstgelegener Markt',
    allBranches: 'Alle Märkte',
    hours: 'Öffnungszeiten',
    today: 'Heute',
    call: 'Anrufen',
    route: 'Route',
    distanceAway: (km: string) => `${km} km entfernt`,
    locationHint: 'Aktivieren Sie den Standortzugriff, um den nächstgelegenen Markt zu sehen.',
  },
  angebote: {
    title: 'Angebote',
    allCategories: 'Alle',
    addToList: 'Zur Liste',
    added: 'Hinzugefügt',
    validUntil: (date: string) => `Gültig bis ${date}`,
    searchPlaceholder: 'Produkte durchsuchen',
  },
  liste: {
    title: 'Einkaufsliste',
    empty: 'Ihre Einkaufsliste ist leer',
    emptyHint: 'Fügen Sie Artikel über Angebote oder Produkte hinzu.',
    share: 'Teilen',
    total: 'Gesamt',
    clear: 'Liste leeren',
    searchPlaceholder: 'Suchen, um Artikel hinzuzufügen',
    notAvailable: 'Aktuell nicht verfügbar',
    availableInAll: 'Verfügbar in allen Filialen',
    availableInSome: (count: number, total: number) => `Verfügbar in ${count} von ${total} Filialen`,
    planVisit: 'Filialbesuch planen',
    checkoutInStore: 'Checkout in der Filiale',
    requestDelivery: 'Lieferung anfragen',
  },
  scanner: {
    title: 'Scanner',
    hint: 'Barcode scannen',
    permissionTitle: 'Kamerazugriff erforderlich',
    permissionHint: 'Um Produkte zu scannen, benötigen wir Zugriff auf Ihre Kamera.',
    permissionButton: 'Zugriff erlauben',
    notFoundTitle: 'Produkt nicht gefunden',
    notFoundHint: 'Dieser Barcode ist uns nicht bekannt.',
    scanAgain: 'Erneut scannen',
    explainerTitle: 'So funktioniert der Scanner',
    explainerHint: 'Richten Sie die Kamera auf den Barcode eines Produkts, um Preis und Verfügbarkeit zu sehen.',
    explainerStart: 'Scanner starten',
    explainerDontShow: 'Nicht mehr anzeigen',
    cartSummary: (count: number, total: string) => `${count} Artikel im Warenkorb · ${total}`,
    addToCart: 'Zum Warenkorb',
    addedToCart: 'Hinzugefügt',
    youAreHere: (branchName: string) => `Sie sind hier: ${branchName}`,
  },
  standort: {
    title: 'Standort wählen',
    explanation:
      'In einer echten App würde Ihr GPS-Standort automatisch ermittelt, um zu prüfen, ob Sie sich in einer Filiale befinden. Für diesen Prototyp wählen Sie Ihren Standort bitte manuell – diese Auswahl gilt für die gesamte Sitzung.',
    awayOption: 'Nicht in der Filiale',
    awayHint: 'Zuhause oder unterwegs',
    inStoreLabel: 'In der Filiale',
  },
  rechnungen: {
    title: 'Rechnungen',
    filterByMarket: 'Markt',
    filterByDate: 'Datum',
    allMarkets: 'Alle Märkte',
    invoiceNumber: 'Rechnungs-Nr.',
    sortNewest: 'Neueste zuerst',
    sortOldest: 'Älteste zuerst',
    itemsTitle: 'Positionen',
    subtotal: 'Zwischensumme (netto)',
    vat: 'MwSt.',
    total: 'Gesamtbetrag',
    downloadPdf: 'PDF herunterladen',
    empty: 'Noch keine Rechnungen',
    emptyHint: 'Hier erscheinen Ihre Einkäufe nach dem nächsten Besuch in einem Markt.',
  },
  profil: {
    title: 'Profil',
    business: 'Betrieb',
    address: 'Adresse',
    switchBrand: 'Marke wechseln',
    team: 'Digitale Einkaufsvollmacht',
    logout: 'Abmelden',
    demoReset: 'Demo zurücksetzen',
    demoResetConfirm: 'Möchten Sie alle Demo-Daten zurücksetzen?',
  },
  produkt: {
    title: 'Produktbeschreibung',
    generalInfo: 'Allgemeine Informationen',
    productGroup: 'Produktgruppe',
    productSubgroup: 'Untergruppe',
    manufacturerGroup: 'Herstellergruppe',
    sources: 'Bezugsquellen',
    shelfLife: 'Restlaufzeit',
    generalNotes: 'Allgemeine Hinweise',
    storage: 'Lagerhinweise',
    preparation: 'Zubereitungsempfehlung',
    labeling: 'Kennzeichnung',
    customsTariffNumber: 'Zolltarifnummer',
    manufacturerLabel: 'Verantwortlicher Lebensmittelunternehmer',
    dietaryInfo: 'Kostformen',
    packagingUnits: 'Packungseinheiten',
    salesUnit: 'Verkaufseinheit',
    singleUnit: 'Einzelpackung / -einheit',
    type: 'Typ',
    gtin: 'GTIN-Nr.',
    quantityPerSalesUnit: 'Anzahl Einzel pro Verkaufseinheit',
    grossWeight: 'Bruttogewicht',
    netWeight: 'Nettogewicht',
    dimensions: 'Abmessungen in mm (LxBxH)',
    notAvailable: 'Für dieses Produkt sind keine weiteren Informationen verfügbar.',
  },
  rueckverguetung: {
    title: 'Rückvergütung',
    totalSpend: 'Gesamtumsatz',
    cashbackSoFar: 'Rückvergütung bisher',
    currentRateNote: (rate: number) => `bei ${rate}% Rückvergütung`,
    progressTitle: 'Ihr Weg zur nächsten Stufe',
    nextMilestone: (remaining: string, rate: number) => `Noch ${remaining} € bis ${rate}% Rückvergütung`,
    maxReached: 'Sie haben die höchste Stufe erreicht 🎉',
    tiersTitle: 'Rückvergütungsstufen',
    tierReached: 'Erreicht',
  },
  filialbesuch: {
    title: 'Filialbesuch planen',
    subtitle: 'Wir zeigen Ihnen, in welcher Filiale Sie die meisten Artikel Ihrer Liste bekommen.',
    bestMatch: 'Beste Übereinstimmung',
    itemsAvailable: (count: number, total: number) => `${count} von ${total} Artikeln verfügbar`,
    allAvailable: 'Alle Artikel verfügbar',
    noneAvailable: 'Keine Artikel verfügbar',
    missingItemsTitle: 'Nicht verfügbar in dieser Filiale',
    route: 'Route',
    call: 'Anrufen',
    empty: 'Ihre Einkaufsliste ist leer',
    emptyHint: 'Fügen Sie Artikel zu Ihrer Liste hinzu, um einen Filialbesuch zu planen.',
  },
  lieferung: {
    title: 'Lieferung anfragen',
    subtitle: 'Lassen Sie sich die Artikel Ihrer Liste an Ihren Betrieb liefern.',
    itemsTitle: 'Ihre Bestellung',
    deliveryAddress: 'Lieferadresse',
    branchLabel: 'Lieferung aus',
    submit: 'Lieferung anfragen',
    successTitle: 'Deine Lieferung wird vorbereitet',
    successHint: 'Dein Markt hat die Anfrage erhalten und bereitet alles für die Lieferung vor.',
    done: 'Fertig',
    empty: 'Ihre Einkaufsliste ist leer',
    emptyHint: 'Fügen Sie Artikel zu Ihrer Liste hinzu, um eine Lieferung anzufragen.',
  },
  kasse: {
    title: 'Kasse',
    subtitle: 'Zeigen Sie diesen Code an der Kasse vor',
    itemsTitle: 'Ihr Warenkorb',
    total: 'Gesamtbetrag',
    payButton: 'Als bezahlt markieren',
    successTitle: 'Vielen Dank!',
    successHint: 'Ihr Einkauf wurde abgeschlossen.',
    done: 'Fertig',
    empty: 'Ihr Warenkorb ist leer',
    emptyHint: 'Scannen Sie Artikel im Markt, um sie hinzuzufügen.',
  },
  listeKasse: {
    title: 'Kasse',
    subtitle: 'Aktivieren Sie Bluetooth und zeigen Sie Ihren Karten-Code an der Kasse vor, um Ihre Liste zu übernehmen.',
    itemsTitle: 'Ihre Einkaufsliste',
    total: 'Gesamtbetrag',
    activateBluetooth: 'Bluetooth aktivieren',
    bluetoothActive: 'Bluetooth aktiv',
    showCardCode: 'Karten-Code anzeigen',
    cardCodeTitle: 'Karten-Code',
    cardCodeHint: 'Lassen Sie diesen Code an der Kasse scannen, um Ihre Liste im System zu validieren.',
    paySimulateHint: 'Demo-Simulation · aktualisiert Inventar & Rechnungen',
    empty: 'Ihre Einkaufsliste ist leer',
    emptyHint: 'Fügen Sie Artikel zu Ihrer Liste hinzu, bevor Sie zur Kasse gehen.',
  },
  team: {
    title: 'Digitale Einkaufsvollmacht',
    subtitle: 'Autorisieren Sie Kolleg:innen, mit Ihrer Kundenkarte in der Filiale einzukaufen.',
    addButton: 'Kolleg:in bevollmächtigen',
    limitReached: (max: number) => `Maximal ${max} Autorisierungen gleichzeitig möglich.`,
    empty: 'Noch keine Kolleg:innen autorisiert',
    emptyHint: 'Fügen Sie Teammitglieder hinzu, die mit Ihrer Kundenkarte einkaufen dürfen.',
    nameLabel: 'Name',
    namePlaceholder: 'Vor- und Nachname',
    emailLabel: 'E-Mail-Adresse',
    emailPlaceholder: 'name@beispiel.de',
    validityLabel: 'Gültigkeitszeitraum',
    startsIn: 'Beginnt',
    startsInValue: (days: number) => (days === 0 ? 'Heute' : days === 1 ? 'in 1 Tag' : `in ${days} Tagen`),
    duration: 'Dauer',
    durationValue: (days: number) => (days === 1 ? '1 Tag' : `${days} Tage`),
    validRange: (from: string, to: string) => `Gültig von ${from} bis ${to}`,
    submit: 'Autorisieren',
    cancel: 'Abbrechen',
    statusActive: 'Aktiv',
    statusPending: 'Geplant',
    statusExpired: 'Abgelaufen',
    revoke: 'Entziehen',
    invitedTitle: 'Einladung gesendet',
    invitedHint: (email: string) =>
      `Eine Aktivierungs-E-Mail wurde an ${email} gesendet (simuliert). Nach Bestätigung kann diese Person Ihre Kundenkarte im gewählten Zeitraum verwenden.`,
  },
  inventar: {
    title: 'Inventar',
    posSection: 'Kassenabschluss heute',
    posTitle: 'Tagesverkauf',
    stockSection: 'Lagerbestand · kritisch zuerst',
    criticalAlert: 'Nachbestellen empfohlen',
  },
} as const;
